# Generated by Django 5.1 on 2024-08-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_weight', models.IntegerField()),
                ('product_available', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], default='IN STOCK', max_length=255)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
