# Generated by Django 5.1 on 2024-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_alter_product_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admindashboard.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_State',
            field=models.CharField(choices=[('RECENT PRODUCT', 'RECENT PRODUCT'), ('FEATURED_PRODUCT', 'FEATURED_PRODUCT'), ('TRENDING_PRODUCT', 'TRENDING_PRODUCT'), ('NEW_PRODUCR_ARRIVALS', 'NEW_PRODUCR_ARRIVALS')], default='FEATURED_PRODUCT', max_length=255),
        ),
    ]
