# Generated by Django 5.1 on 2024-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_delete_movieproxy_remove_product_product_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChoicesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RECENT PRODUCT', 'Recent Product'), ('FEATURED PRODUCT', 'Featured Product'), ('TRENDING PRODUCT', 'Trending Product'), ('NEW PRODUCT ARRIVALS', 'New Product Arrivals')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_state',
        ),
        migrations.AddField(
            model_name='product',
            name='product_state',
            field=models.ManyToManyField(blank=True, to='admindashboard.statechoicestag'),
        ),
    ]
